import type { WeeklyImageCredit } from "@/domain/types";

export interface SourcedImage {
  poster: string;
  thumb: string;
  focalPoint?: { x: number; y: number };
  credit: WeeklyImageCredit;
}

/**
 * Weekly images — real, openly licensed files from Wikimedia Commons, each
 * from a named medical/scientific origin (OpenStax, Blausen Medical,
 * pathologists' specimen photos, clinicians' ultrasound scans). None are
 * generated. Posters are letterboxed (never cropped) to 4:5; the week-32 scan
 * has its header cropped to remove a patient name. When no image exists for
 * the exact week, `depicts` states the true age of the nearest one.
 * Regenerate files with the import step documented in docs/fetal-development-sources.md.
 */
export const SOURCED_IMAGES: Record<number, SourcedImage> = {
  0: { poster: "/media/weekly/week-00.poster.webp", thumb: "/media/weekly/week-00.thumb.webp", credit: {"depicts": "رسم علمي لدورة المبيض والدورة الشهرية مع الهرمونات", "author": "OpenStax College", "license": "CC BY 4.0", "sourceUrl": "https://commons.wikimedia.org/wiki/File:Figure_28_02_07.jpg", "licenseUrl": "https://creativecommons.org/licenses/by/4.0"} },
  1: { poster: "/media/weekly/week-01.poster.webp", thumb: "/media/weekly/week-01.thumb.webp", credit: {"depicts": "رسم علمي لمراحل نضوج جريبات المبيض حتى الإباضة", "author": "OpenStax College", "license": "CC BY 3.0", "sourceUrl": "https://commons.wikimedia.org/wiki/File:Stages_of_folliculogenesis.jpg", "licenseUrl": "https://creativecommons.org/licenses/by/3.0"} },
  2: { poster: "/media/weekly/week-02.poster.webp", thumb: "/media/weekly/week-02.thumb.webp", credit: {"depicts": "صورة مجهرية حقيقية لبويضة بشرية في مختبر أطفال الأنابيب", "author": "ZEISS Microscopy", "license": "CC BY-SA 2.0", "sourceUrl": "https://commons.wikimedia.org/wiki/File:Oocyte_with_Zona_pellucida_(27771482282).jpg", "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0"} },
  3: { poster: "/media/weekly/week-03.poster.webp", thumb: "/media/weekly/week-03.thumb.webp", credit: {"depicts": "صورة مجهرية حقيقية للاقحة بشرية في يومها الأول بعد الإخصاب", "author": "NinaSes", "license": "CC BY-SA 4.0", "sourceUrl": "https://commons.wikimedia.org/wiki/File:%D0%AD%D0%BC%D0%B1%D1%80%D0%B8%D0%BE%D0%BD_%D1%87%D0%B5%D0%BB%D0%BE%D0%B2%D0%B5%D0%BA%D0%B0_%D0%BF%D0%B5%D1%80%D0%B2%D1%8B%D0%B5_%D1%81%D1%83%D1%82%D0%BA%D0%B8_%D1%80%D0%B0%D0%B7%D0%B2%D0%B8%D1%82%D0%B8%D1%8F.png", "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"} },
  4: { poster: "/media/weekly/week-04.poster.webp", thumb: "/media/weekly/week-04.thumb.webp", credit: {"depicts": "رسم علمي لانغراس الكيسة الأريمية في بطانة الرحم", "author": "OpenStax College", "license": "CC BY 3.0", "sourceUrl": "https://commons.wikimedia.org/wiki/File:2905_Implantation.jpg", "licenseUrl": "https://creativecommons.org/licenses/by/3.0"} },
  5: { poster: "/media/weekly/week-05.poster.webp", thumb: "/media/weekly/week-05.thumb.webp", credit: {"depicts": "سونار مهبلي لمضغة في الأسبوع 5 مع كيس المحّ", "author": "X.Compagnion", "license": "CC BY 2.5", "sourceUrl": "https://commons.wikimedia.org/wiki/File:Embryo_at_5_weeks.JPG", "licenseUrl": "https://creativecommons.org/licenses/by/2.5"} },
  6: { poster: "/media/weekly/week-06.poster.webp", thumb: "/media/weekly/week-06.thumb.webp", credit: {"depicts": "صورة حقيقية لمضغة بعمر نحو 5–6 أسابيع (من حمل خارج الرحم)", "author": "lunar caustic", "license": "CC BY 2.0", "sourceUrl": "https://commons.wikimedia.org/wiki/File:Embryo_3_to_4_weeks.jpg", "licenseUrl": "https://creativecommons.org/licenses/by/2.0"} },
  7: { poster: "/media/weekly/week-07.poster.webp", thumb: "/media/weekly/week-07.thumb.webp", credit: {"depicts": "صورة حقيقية لمضغة بطول 10 مم في الأسبوع 7 (من حمل خارج الرحم)", "author": "Ed Uthman, MD", "license": "Public domain", "sourceUrl": "https://commons.wikimedia.org/wiki/File:Tubal_Pregnancy_with_embryo.jpg"} },
  8: { poster: "/media/weekly/week-08.poster.webp", thumb: "/media/weekly/week-08.thumb.webp", credit: {"depicts": "صورة حقيقية لمضغة بعمر نحو 8 أسابيع داخل كيس الحمل", "author": "lunar caustic", "license": "CC BY 2.0", "sourceUrl": "https://commons.wikimedia.org/wiki/File:Human_Embryo_-_Approximately_8_weeks_estimated_gestational_age.jpg", "licenseUrl": "https://creativecommons.org/licenses/by/2.0"} },
  9: { poster: "/media/weekly/week-09.poster.webp", thumb: "/media/weekly/week-09.thumb.webp", credit: {"depicts": "صورة حقيقية لمضغة بحجم يعادل الأسبوع 9 (من حمل خارج الرحم)", "author": "Ed Uthman, MD", "license": "CC BY 2.0", "sourceUrl": "https://commons.wikimedia.org/wiki/File:9-Week_Human_Embryo_from_Ectopic_Pregnancy.jpg", "licenseUrl": "https://creativecommons.org/licenses/by/2.0"} },
  10: { poster: "/media/weekly/week-10.poster.webp", thumb: "/media/weekly/week-10.thumb.webp", credit: {"depicts": "صورة حقيقية لجنين بعمر نحو 10 أسابيع داخل كيس الحمل", "author": "lunar caustic", "license": "CC BY 2.0", "sourceUrl": "https://commons.wikimedia.org/wiki/File:Embryo_approximately_8_weeks_from_conception,_10_weeks_estimated_gestational_age_from_LMP.jpg", "licenseUrl": "https://creativecommons.org/licenses/by/2.0"} },
  11: { poster: "/media/weekly/week-11.poster.webp", thumb: "/media/weekly/week-11.thumb.webp", credit: {"depicts": "سونار لجنين في الأسبوع 11", "author": "X.Compagnion", "license": "Public domain", "sourceUrl": "https://commons.wikimedia.org/wiki/File:Embryo_at_11_weeks.JPG"} },
  12: { poster: "/media/weekly/week-12.poster.webp", thumb: "/media/weekly/week-12.thumb.webp", credit: {"depicts": "سونار لجنين بعمر 12 أسبوعاً و3 أيام مع قياس الطول", "author": "Wolfgang Moroder", "license": "CC BY-SA 3.0", "sourceUrl": "https://commons.wikimedia.org/wiki/File:CRL_Crown_rump_length_12_weeks_ecografia_Dr._Wolfgang_Moroder.jpg", "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0"} },
  13: { poster: "/media/weekly/week-13.poster.webp", thumb: "/media/weekly/week-13.thumb.webp", credit: {"depicts": "سونار لجنين بعمر 13 أسبوعاً و3 أيام (فحص الشفافية القفوية)", "author": "Wolfgang Moroder", "license": "CC BY-SA 3.0", "sourceUrl": "https://commons.wikimedia.org/wiki/File:Nuchal_translucency_Dr._Wolfgang_Moroder.jpg", "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0"} },
  14: { poster: "/media/weekly/week-14.poster.webp", thumb: "/media/weekly/week-14.thumb.webp", credit: {"depicts": "سونار لوجه جنين في الأسبوع 14", "author": "myllissa (Flickr); uploaded by Rizome", "license": "CC BY-SA 2.0", "sourceUrl": "https://commons.wikimedia.org/wiki/File:Ecograf%C3%ADa_2D_-_Feto_14semanas_A.jpg", "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0"} },
  15: { poster: "/media/weekly/week-15.poster.webp", thumb: "/media/weekly/week-15.thumb.webp", credit: {"depicts": "سونار لجنين بعمر 16 أسبوعاً ويوم (أقرب صورة متاحة للأسبوع 15)", "author": "Nevit Dilmen", "license": "CC BY-SA 3.0", "sourceUrl": "https://commons.wikimedia.org/wiki/File:Ultrasound_Scan_ND_114.jpg", "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0"} },
  16: { poster: "/media/weekly/week-16.poster.webp", thumb: "/media/weekly/week-16.thumb.webp", credit: {"depicts": "سونار لجنين بعمر 16 أسبوعاً و6 أيام", "author": "Nevit Dilmen", "license": "CC BY-SA 3.0", "sourceUrl": "https://commons.wikimedia.org/wiki/File:Ultrasound_Scan_ND_126.jpg", "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0"} },
  17: { poster: "/media/weekly/week-17.poster.webp", thumb: "/media/weekly/week-17.thumb.webp", credit: {"depicts": "سونار لجنين بعمر 17 أسبوعاً", "author": "Guimi", "license": "CC BY-SA 2.5", "sourceUrl": "https://commons.wikimedia.org/wiki/File:Scan17semanas1.png", "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.5"} },
  18: { poster: "/media/weekly/week-18.poster.webp", thumb: "/media/weekly/week-18.thumb.webp", credit: {"depicts": "سونار لجنين في الأسبوع 18", "author": "robmcbell (Flickr)", "license": "CC BY-SA 2.0", "sourceUrl": "https://commons.wikimedia.org/wiki/File:18_Week_Ultrasound_(4974224706).jpg", "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0"} },
  19: { poster: "/media/weekly/week-19.poster.webp", thumb: "/media/weekly/week-19.thumb.webp", credit: {"depicts": "سونار لرأس جنين بعمر 19 أسبوعاً ويومين (سونار التشوهات)", "author": "Wolfgang Moroder", "license": "CC BY-SA 3.0", "sourceUrl": "https://commons.wikimedia.org/wiki/File:Cervelletto_e_cisterna_magna_ecografia_ad_ultrasuoni_Dr._Wolfgang_Moroder.jpg", "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0"} },
  20: { poster: "/media/weekly/week-20.poster.webp", thumb: "/media/weekly/week-20.thumb.webp", credit: {"depicts": "سونار لجنين بعمر 20 أسبوعاً ويوم", "author": "Guimi", "license": "CC BY-SA 2.5", "sourceUrl": "https://commons.wikimedia.org/wiki/File:Scan20semanas1.png", "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.5"} },
  21: { poster: "/media/weekly/week-21.poster.webp", thumb: "/media/weekly/week-21.thumb.webp", credit: {"depicts": "سونار لجنين في الأسبوع 21", "author": "Jmurcia", "license": "CC BY-SA 3.0", "sourceUrl": "https://commons.wikimedia.org/wiki/File:Ecografia_21setmanes.JPG", "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0"} },
  22: { poster: "/media/weekly/week-22.poster.webp", thumb: "/media/weekly/week-22.thumb.webp", credit: {"depicts": "سونار لملامح وجه جنين في الأسبوع 22", "author": "X.Compagnion", "license": "Public domain", "sourceUrl": "https://commons.wikimedia.org/wiki/File:Fetal_face_profile.jpg"} },
  23: { poster: "/media/weekly/week-23.poster.webp", thumb: "/media/weekly/week-23.thumb.webp", credit: {"depicts": "سونار لجنين بعمر 23 أسبوعاً و3 أيام", "author": "Nevit Dilmen", "license": "CC BY-SA 3.0", "sourceUrl": "https://commons.wikimedia.org/wiki/File:Ultrasound_Scan_ND_060.jpg", "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0"} },
  24: { poster: "/media/weekly/week-24.poster.webp", thumb: "/media/weekly/week-24.thumb.webp", credit: {"depicts": "سونار ثلاثي الأبعاد لوجه جنين بعمر 24 أسبوعاً و3 أيام", "author": "Prskavka", "license": "Public domain", "sourceUrl": "https://commons.wikimedia.org/wiki/File:3Dultrasound_24weeks_+3.jpg"} },
  25: { poster: "/media/weekly/week-25.poster.webp", thumb: "/media/weekly/week-25.thumb.webp", credit: {"depicts": "سونار لجنين بعمر 25 أسبوعاً ويومين", "author": "Nevit Dilmen", "license": "CC BY-SA 3.0", "sourceUrl": "https://commons.wikimedia.org/wiki/File:Ultrasound_Scan_ND_081.jpg", "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0"} },
  26: { poster: "/media/weekly/week-26.poster.webp", thumb: "/media/weekly/week-26.thumb.webp", credit: {"depicts": "سونار لجنين بعمر 26 أسبوعاً و6 أيام", "author": "Nevit Dilmen", "license": "CC BY-SA 3.0", "sourceUrl": "https://commons.wikimedia.org/wiki/File:Ultrasound_Scan_ND_065.jpg", "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0"} },
  27: { poster: "/media/weekly/week-27.poster.webp", thumb: "/media/weekly/week-27.thumb.webp", credit: {"depicts": "سونار ثلاثي الأبعاد لوجه جنين بعمر 27 أسبوعاً و4 أيام", "author": "PetrosZarganis", "license": "CC BY-SA 4.0", "sourceUrl": "https://commons.wikimedia.org/wiki/File:27%CE%B5%CE%B2%CE%B44%CE%B7%CE%BC%CE%95%CE%BC%CE%B2%CF%81%CF%85%CE%BF%CE%A0%CE%96_1.jpg", "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"} },
  28: { poster: "/media/weekly/week-28.poster.webp", thumb: "/media/weekly/week-28.thumb.webp", credit: {"depicts": "سونار لجنين بعمر 28 أسبوعاً ويوم", "author": "Nevit Dilmen", "license": "CC BY-SA 3.0", "sourceUrl": "https://commons.wikimedia.org/wiki/File:Ultrasound_Scan_ND_083.jpg", "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0"} },
  29: { poster: "/media/weekly/week-29.poster.webp", thumb: "/media/weekly/week-29.thumb.webp", credit: {"depicts": "سونار لجنين بعمر 29 أسبوعاً", "author": "Nevit Dilmen", "license": "CC BY-SA 3.0", "sourceUrl": "https://commons.wikimedia.org/wiki/File:Ultrasound_Scan_ND_112.jpg", "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0"} },
  30: { poster: "/media/weekly/week-30.poster.webp", thumb: "/media/weekly/week-30.thumb.webp", credit: {"depicts": "سونار لجنين بعمر 30 أسبوعاً ويومين", "author": "Nevit Dilmen", "license": "CC BY-SA 3.0", "sourceUrl": "https://commons.wikimedia.org/wiki/File:Ultrasound_Scan_ND_146.jpg", "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0"} },
  31: { poster: "/media/weekly/week-31.poster.webp", thumb: "/media/weekly/week-31.thumb.webp", credit: {"depicts": "سونار لجنين بعمر 30 أسبوعاً ويومين (أقرب صورة متاحة للأسبوع 31)", "author": "Nevit Dilmen", "license": "CC BY-SA 3.0", "sourceUrl": "https://commons.wikimedia.org/wiki/File:Ultrasound_Scan_ND_146.jpg", "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0"} },
  32: { poster: "/media/weekly/week-32.poster.webp", thumb: "/media/weekly/week-32.thumb.webp", credit: {"depicts": "سونار لجنين بعمر 32 أسبوعاً و5 أيام، مقصوصة لإخفاء بيانات المريضة", "author": "robmcbell (Flickr)", "license": "CC BY-SA 2.0", "sourceUrl": "https://commons.wikimedia.org/wiki/File:Ultrasound_(5323400577).jpg", "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0"} },
  33: { poster: "/media/weekly/week-33.poster.webp", thumb: "/media/weekly/week-33.thumb.webp", credit: {"depicts": "سونار لجنين في الأسبوع 33 مع قياس نبض القلب", "author": "Nevit Dilmen", "license": "CC BY-SA 3.0", "sourceUrl": "https://commons.wikimedia.org/wiki/File:Ultrasound_Scan_ND_045.jpg", "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0"} },
  34: { poster: "/media/weekly/week-34.poster.webp", thumb: "/media/weekly/week-34.thumb.webp", credit: {"depicts": "سونار لكليتي جنين بعمر 34 أسبوعاً و4 أيام", "author": "Nevit Dilmen", "license": "CC BY-SA 3.0", "sourceUrl": "https://commons.wikimedia.org/wiki/File:Ultrasound_Scan_ND_122.jpg", "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0"} },
  35: { poster: "/media/weekly/week-35.poster.webp", thumb: "/media/weekly/week-35.thumb.webp", credit: {"depicts": "سونار لجنين بعمر 35 أسبوعاً", "author": "Nevit Dilmen", "license": "CC BY-SA 3.0", "sourceUrl": "https://commons.wikimedia.org/wiki/File:Ultrasound_Scan_ND_661.jpg", "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0"} },
  36: { poster: "/media/weekly/week-36.poster.webp", thumb: "/media/weekly/week-36.thumb.webp", credit: {"depicts": "سونار لرأس جنين بعمر 36 أسبوعاً ويوم مع قياس محيط الرأس", "author": "Nevit Dilmen", "license": "CC BY-SA 3.0", "sourceUrl": "https://commons.wikimedia.org/wiki/File:Ultrasound_Scan_ND_048.jpg", "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0"} },
  37: { poster: "/media/weekly/week-37.poster.webp", thumb: "/media/weekly/week-37.thumb.webp", credit: {"depicts": "سونار لعمود فقري جنين بعمر 36 أسبوعاً ويومين (أقرب صورة متاحة للأسبوع 37)", "author": "Nevit Dilmen", "license": "CC BY-SA 3.0", "sourceUrl": "https://commons.wikimedia.org/wiki/File:Ultrasound_Scan_ND_151.jpg", "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0"} },
  38: { poster: "/media/weekly/week-38.poster.webp", thumb: "/media/weekly/week-38.thumb.webp", credit: {"depicts": "سونار لجنين بعمر 39 أسبوعاً مع قياس نبض القلب (أقرب صورة متاحة للأسبوع 38)", "author": "Nevit Dilmen", "license": "CC BY-SA 3.0", "sourceUrl": "https://commons.wikimedia.org/wiki/File:Ultrasound_Scan_ND_150.jpg", "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0"} },
  39: { poster: "/media/weekly/week-39.poster.webp", thumb: "/media/weekly/week-39.thumb.webp", credit: {"depicts": "سونار لجنين بعمر 39 أسبوعاً مع قياس نبض القلب", "author": "Nevit Dilmen", "license": "CC BY-SA 3.0", "sourceUrl": "https://commons.wikimedia.org/wiki/File:Ultrasound_Scan_ND_150.jpg", "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0"} },
  40: { poster: "/media/weekly/week-40.poster.webp", thumb: "/media/weekly/week-40.thumb.webp", credit: {"depicts": "رسم طبي لحمل مكتمل: الجنين ورأسه للأسفل مع المشيمة والحبل السري", "author": "Blausen Medical (2014), WikiJournal of Medicine", "license": "CC BY 3.0", "sourceUrl": "https://commons.wikimedia.org/wiki/File:Blausen_0747_Pregnancy.png", "licenseUrl": "https://creativecommons.org/licenses/by/3.0"} },
};
